final String host = "http://192.168.0.111:8080";
final String loginApi = host+ "/login";
final String registerApi = host+ "/saveUsers";
final String getAllProductApi = host+ "/product/getAll";
final String getProductByIdApi = host+ "/product/getOne/";
final String getProductByCateIdApi = host+ "/product/ByCategoryId/";
final String addToCartApi = host+ "/cart/save";
final String getCartItemsApi = host+ "/cart/getAll";
final String deleteCartByIdApi = host+ "/cart/delete/";
